#!/bin/sh

running=$(pgrep -f "/bin/sh $0" | wc -l)

if [ $running -eq 2 ]; then
    systemctl --user start peerbanhelper.service
    qbittorrent $1
    systemctl --user stop peerbanhelper.service
fi
